### ISSUE TITLE
Font artifacts on Radeon RX 5700

### ISSUE THREAD

**Issue by alnyan** [hakolao/egui_winit_vulkano#16]
OS: Arch Linux
egui_winit_vulkano version: 0.17.0
Graphics card: Radeon RX 5700 (Free driver + vulkan-radeon)

I'm currently observing color artifacts with label/button fonts when using RX 5700, yet the issue does not reproduce on Ryzen 4700U's integrated GPU.

GUI is setup with `is_overlay = false` and I used minimal.rs as an example.

I'm not sure if this is the correct crate to open the issue, but I don't really know whether the issue is in the integration or in egui itself.

**Comment by alnyan** [comment]
Here are two screenshots for comparison, first one taken from RX 5700 test, second one from Ryzen 4700U IGPU
![photo_RX5700](https://user-images.githubusercontent.com/3716812/179578234-e7b2c78c-bd23-4bb4-8142-a018d35fffec.jpg)
![photo_Ryzen4700U](https://user-images.githubusercontent.com/3716812/179578248-bb3f88d0-76c5-4bb9-8801-811db308c9d3.jpg)

**Comment by hakolao** [comment]
Are you using the crates version or the newest master branch? (Havent bumped the version number yet).

if it’s not the master branch one, do you see the issue there too?

Hard to say though. I’d need to figure out a way to reproduce it.

Does it happen on any other integration? E.g https://github.com/emilk/egui/tree/master/egui-wgpu just to see if it seems specific to my integration.

**Comment by alnyan** [comment]
Just tested master egui_winit_vulkano with its Cargo.toml revision of vulkano libs, same issue. Did not yet test egui with wgpu backend, as my project is developed using vulkano as a backend.

**Comment by hakolao** [comment]
Some fonts work, but only the label + buttons not?

**Comment by alnyan** [comment]
No, all the components with text I tested so far have this issue

**Comment by hakolao** [comment]
I was thinking that the wgpu integration test could help pinpoint if it’s vulkan (you can select vulkan backend with it) or egui. And then if it does not show there, then it’s probably bug in this integration.

**Comment by hakolao** [comment]
Anyway, I can try to see tomorrow if I can find out probable causes

**Comment by alnyan** [comment]
Tried https://github.com/hasenbanck/egui_example, works fine. Still not sure if I am doing something wrong in my setup with vulkano. 
Thanks for looking into this issue!

**Comment by hakolao** [comment]
Would you be able to attempt with the branch from #17. Let me know if it changes anything for you. It might not...

**Comment by alnyan** [comment]
Just tried, unfortunately, did not help

**Comment by alnyan** [comment]
Also, the button texture itself seems fine, it's only fonts that get these artifacts. So I think, there might be some problem with TTF stuff specific to my setup. I will try to experiment with different fonts to see if that changes anything

**Comment by hakolao** [comment]
Alright!

**Comment by alnyan** [comment]
I seem to have found the likely cause of the problem: with RX 5700, my output format is A2R10G10B10 (sRGB), whereas with Ryzen 4700U IGPU it's B8G8R8A8. I also noticed that other egui integration libraries do some sRGB-specific conversions in their shaders, so doing the same thing might actually fix the problem.

**Comment by hakolao** [comment]
Want to try a fix? :)

**Comment by alnyan** [comment]
Sure. I'll try to port shaders from other crates and see if it fixes the problem

**Comment by hakolao** [comment]
I merged the little PR anyway, as I had been thinking of doing that earlier, even though it did nothing to address this issue. I added also a new example to run the `egui_demo_app` so it's better to check everything works correct if you end up fixing this

**Comment by hakolao** [comment]
This issue should then be resolved, other than the `SRGB` conversions. I might have to try if I can find a consistent solution to that.

Let me know if you run into anything else!
