### ISSUE TITLE
A panic when running on android.

### ISSUE THREAD

**Issue by Kirottu** [hakolao/egui_winit_vulkano#26]
I have been trying to get an app to run with vulkano, winit and egui on android. It compiles fine but when it starts on my phone it has this error: 
```thread '<unnamed>' panicked at 'Cannot get the native window, it's null and will always be null before Event::Resumed and after Event::Suspended. Make sure you only call this function between those events.'```

**Comment by hakolao** [comment]
Have you managed to get a basic vulkano example running? Just wondering if it is there or winit, egui or this lib.

I don’t have a debugging setup for android unfortunately, so hard to say directly.

**Comment by Kirottu** [comment]
Ok well it seems like no example using winit works. Everything seems to fail with this error.

**Comment by hakolao** [comment]
Might be better to report it to winit then

**Comment by Kirottu** [comment]
Yes I did so

**Comment by Kirottu** [comment]
Alright I managed to get it working with wgpu after some wrangling, thanks anyway.

**Comment by hakolao** [comment]
Great! :)
