### ISSUE TITLE
Re-assign the subpass after creation

### ISSUE THREAD

**Issue by Mercadud** [hakolao/egui_winit_vulkano#32]
I might be getting vulkano and this library wrong but, I want to switch between render passes, but to make any of those changes requires me to reassign the subpass to the Gui struct, Is there a way to do it?

**Comment by hakolao** [comment]
I am not quite sure what you are asking. Wanna give me more information? ;)

You can use this library either as its own render pass (meaning this library just renders over after anything you render) or then as a subpass (belonging to your own render pass). Both of these ways can be found in the examples.

**Comment by Mercadud** [comment]
I must be getting vulkan wrong then at the moment, I'll do more research first before reopening the issue.

**Comment by ColonelThirtyTwo** [comment]
This should be added. Pipelines may be created with fixed sizes and recreated when resize events come in - see the [Vulkano teapot example](https://github.com/vulkano-rs/vulkano/blob/v0.32.0/examples/src/bin/teapot/main.rs#L439). Recreating the egui renderer each resize would mean resetting all of egui's state, which is unacceptable.
