### ISSUE TITLE
Antialiasing?

### ISSUE THREAD

**Issue by Mg138** [hakolao/egui_winit_vulkano#36]
Is text anti-aliasing a thing?

![image](https://user-images.githubusercontent.com/33348966/215262468-721c3d9c-6fe1-431e-bb04-716a736d4d9b.png)

Text don't seem to render too well.

**Comment by hakolao** [comment]
Does this happen in the examples also?

**Comment by Mg138** [comment]
No, we figured that it seems to be a problem with coloured text.

We hacked together a fork, the tl;dr is that we just remove the SRGB conversion stuff.

**Comment by hakolao** [comment]
The SRGB conversion in the shader is used only if the surface format being passed to the library is of linear type.

Colors should work fine too. Try passing the `preferred_format` (of the swapchain image format) to the `Gui::new()`.

See example `demo_app.rs`.

**Comment by Mg138** [comment]
Preferred format fixes it, yes, but then transparency seems wrong. demo_app.rs seems to not have transparency?

Strictly speaking, we're using a more light-mode theming.

**Comment by Mg138** [comment]
We fixed(/hacked) the transparency issue by doing this + removing SRGB conversions:

```rust
let a = v.color.a() as f32 / 255.0;

EguiVertex {
    position: [v.pos.x, v.pos.y],
    tex_coords: [v.uv.x, v.uv.y],
    color: [
        v.color.r() as f32 / 255.0 * a,
        v.color.g() as f32 / 255.0 * a,
        v.color.b() as f32 / 255.0 * a,
        a,
    ],
}
```

**Comment by hakolao** [comment]
It's been a while since I played with the colors, but I never got the color test to match 100% similar to egui web demos.

Anyway, I did notice that the pipeline was potentially using a different alpha blending. Can you try if this branch helps? Along with the preferred format.

#37 

As far as I know, the egui vertex color values shouldn't be multiplied by alpha again. Meaning they say on their github
> egui uses premultiplied alpha

**Comment by hakolao** [comment]
I'd be curious to see a screenshot or a small example of the gui to better understand what you mean with transparency issues. :)

**Comment by Mg138** [comment]
Gonna pull the changes from within my own hack-y fork to test.

(Our code outside is incompatible because of the Multisampling hack-- they're there because otherwise its impossible to multisample on PaintCallbacks)

**Comment by Mg138** [comment]
![image](https://user-images.githubusercontent.com/33348966/216768566-b1a059c2-7e00-41ca-9d6a-eec482353d1c.png)

Hmm...

**Comment by Mg138** [comment]
The passed preferred image format is B8G8R8A8_UNORM

**Comment by Mg138** [comment]
Our code is at https://github.com/Mg138/automancy

It's a bit complicated, we'll make a minimally reproducible example if needed.

**Comment by Mg138** [comment]
We think we'll try to switch to SRGB for now. Maybe say it somewhere to recommend using it?

We think that an option for multisampling states and whatnot would be great!

The hexes aren't really the problem here, enabling multisampling kinda automagically fixed the hexes. The text problem seemed to be entirely about the colorspace. We'll close the issue if switching to SRGB fixes it -- there may be shenanigans going on because of the swapchain format being UNORM?

**Comment by hakolao** [comment]
The swapchain image ahould also be srgb.

**Comment by hakolao** [comment]
I merged my updates & released. I hope that makes this library just a bit more useful for you :).

Added also a multisample example, which is basically similar to subpass one, but mutlisampled.

**Comment by Mg138** [comment]
The game looks very nice now, thanks!
