### ISSUE TITLE
Docs.rs can't compile release 0.24.0

### ISSUE THREAD

**Issue by ryco117** [hakolao/egui_winit_vulkano#46]
When visiting the latest release's page on [docs.rs](https://docs.rs/crate/egui_winit_vulkano/latest) I see the following error message:
![image](https://github.com/hakolao/egui_winit_vulkano/assets/6379289/5f9d0e80-6ee3-48a0-a584-b3332892b14f)

See build logs [here](https://docs.rs/crate/egui_winit_vulkano/0.24.0/builds/782949).

Thanks

**Comment by Letronix624** [comment]
this is fixed
